-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Accounts (Chart of Accounts)
create table accounts (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null check (type in ('asset', 'liability', 'equity', 'revenue', 'expense')),
  code text unique not null,
  balance numeric default 0,
  parent_id bigint references accounts(id),
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Transactions (Income/Expense)
create table transactions (
  id bigint generated by default as identity primary key,
  description text not null,
  amount numeric not null,
  type text not null check (type in ('income', 'expense')),
  date timestamp with time zone not null,
  category text,
  account_id bigint references accounts(id),
  reference text,
  attachments text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Assets
create table assets (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  purchase_price numeric,
  current_value numeric,
  purchase_date timestamp with time zone,
  depreciation_rate numeric,
  condition text,
  location text,
  status text check (status in ('Active', 'Maintenance', 'Disposed')),
  description text,
  serial_number text,
  warranty jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Inventory
create table inventory_items (
  id bigint generated by default as identity primary key,
  sku text unique not null,
  name text not null,
  category text,
  quantity integer default 0,
  reorder_point integer default 0,
  unit_cost numeric default 0,
  sale_price numeric default 0,
  location text,
  status text check (status in ('in-stock', 'low-stock', 'out-of-stock')),
  last_updated timestamp with time zone default timezone('utc'::text, now()) not null
);

create table stock_movements (
  id bigint generated by default as identity primary key,
  item_id bigint references inventory_items(id),
  type text check (type in ('in', 'out', 'adjustment')),
  quantity integer not null,
  reference text,
  notes text,
  cost_per_unit numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Cheques
create table issued_cheques (
  id bigint generated by default as identity primary key,
  cheque_no text not null,
  payee text not null,
  amount numeric not null,
  bank_account_id bigint references accounts(id),
  issue_date date not null,
  status text check (status in ('issued', 'presented', 'cleared', 'bounced')),
  clear_date date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table received_cheques (
  id bigint generated by default as identity primary key,
  cheque_no text not null,
  drawer text not null,
  amount numeric not null,
  bank_name text,
  received_date date not null,
  status text check (status in ('on-hand', 'deposited', 'cleared', 'returned')),
  deposit_date date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Invoicing & AR/AP
create table invoices (
  id bigint generated by default as identity primary key,
  invoice_number text unique not null,
  customer_id uuid, -- Assuming link to profiles or a separate customers table
  date date not null,
  due_date date,
  total_amount numeric default 0,
  status text check (status in ('draft', 'sent', 'paid', 'overdue', 'void')),
  type text check (type in ('invoice', 'bill')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table invoice_items (
  id bigint generated by default as identity primary key,
  invoice_id bigint references invoices(id) on delete cascade,
  description text not null,
  quantity numeric not null,
  unit_price numeric not null,
  total numeric not null
);

-- 7. Settings & Users
create table organization_settings (
  id bigint generated by default as identity primary key,
  company_name text,
  tax_id text,
  address jsonb,
  contact_info jsonb,
  fiscal_year_start text,
  currency text default 'USD',
  date_format text default 'YYYY-MM-DD',
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

create table profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  role text check (role in ('admin', 'accountant', 'viewer')),
  avatar_url text,
  updated_at timestamp with time zone
);

-- 8. Budgets & Recurring
create table budgets (
  id bigint generated by default as identity primary key,
  account_id bigint references accounts(id),
  period text not null, -- Format: YYYY-MM
  amount numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table recurring_transactions (
  id bigint generated by default as identity primary key,
  description text not null,
  amount numeric not null,
  account_id bigint references accounts(id),
  frequency text check (frequency in ('monthly', 'weekly', 'yearly')),
  next_run_date date,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies (Basic Setup - Allow all for now, lock down later)
alter table accounts enable row level security;
create policy "Public accounts access" on accounts for all using (true);

alter table transactions enable row level security;
create policy "Public transactions access" on transactions for all using (true);

alter table assets enable row level security;
create policy "Public assets access" on assets for all using (true);

alter table inventory_items enable row level security;
create policy "Public inventory access" on inventory_items for all using (true);

alter table stock_movements enable row level security;
create policy "Public movements access" on stock_movements for all using (true);

alter table issued_cheques enable row level security;
create policy "Public issued cheques access" on issued_cheques for all using (true);

alter table received_cheques enable row level security;
create policy "Public received cheques access" on received_cheques for all using (true);

alter table invoices enable row level security;
create policy "Public invoices access" on invoices for all using (true);

alter table invoice_items enable row level security;
create policy "Public invoice items access" on invoice_items for all using (true);

alter table organization_settings enable row level security;
create policy "Public settings access" on organization_settings for all using (true);

alter table profiles enable row level security;
create policy "Public profiles access" on profiles for all using (true);

alter table budgets enable row level security;
create policy "Public budgets access" on budgets for all using (true);

alter table recurring_transactions enable row level security;
create policy "Public recurring access" on recurring_transactions for all using (true);
